graph TD
subgraph Data Ingress and Egress
qss[Quantum Safe Storage Engine]
end
subgraph Physical Data storage
st1[Virtual Storage Device 1]
st2[Virtual Storage Device 2]
st3[Virtual Storage Device 3]
st4[Virtual Storage Device 4]
st5[Virtual Storage Device 5]
st6[Virtual Storage Device 6]
st7[Virtual Storage Device 7]
qss -.-> st1 & st2 & st3 & st4 & st5 & st6 & st7
end