name: www3.manual.grid.tf
on:
  push:
    branches: [ development-split ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www3.manual.grid.tf
      uses: appleboy/ssh-action@master
      with:
        host: www3.manual.grid.tf
        username: ${{ secrets.TF_USER }}
        key: ${{ secrets.TF_SECRET }}
        port: ${{ secrets.TF_PORT }}
        script: |
          cd websites/www3/info_grid
          git checkout development-split
          git log -1
          git fetch
          git reset --hard origin/development-split
          make build
          
  wait:
    needs: deploy
    name: Wait for Website Update
    runs-on: ubuntu-latest
    steps:
    - name: Wait Period
      id: wait-deploy
      run: |
        echo "Sleeping for 30"
        sleep 30
        
  checklinks:
    needs: wait
    name: Check for Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Check for Broken Links
        id: link-report
        uses: docker://ghcr.io/threefoldfoundation/website-link-checker:latest
        with:
          args: 'https://www3.manual.grid.tf -e 404 501 503 504 -w all'