name: www3.manual.grid.tf
on:
  push:
    branches: [ development-split ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www3.manual.grid.tf
      uses: appleboy/ssh-action@master
      with:
        host: www3.manual.grid.tf
        username: ${{ secrets.TF_USER }}
        key: ${{ secrets.TF_SECRET }}
        port: ${{ secrets.TF_PORT }}
        script: |
          cd websites/www3/info_grid
          git log -1
          git restore .
          git pull
          mdbook build -d docs
