name: Weekly Link Check
on:
  schedule:
    - cron: '0 6 * * 5'

jobs:
  checkwww:
    name: Check for Broken Links on www
    runs-on: ubuntu-latest
    steps:
      - name: Check for Broken Links on www
        id: link-report www
        uses: docker://ghcr.io/threefoldfoundation/website-link-checker:latest
        with:
          args: 'https://www.manual.grid.tf -e 404 501 503 504 -w all'

  checkwww2:
    name: Check for Broken Links on www2
    runs-on: ubuntu-latest
    steps:
      - name: Check for Broken Links
        id: link-report www2
        uses: docker://ghcr.io/threefoldfoundation/website-link-checker:latest
        with:
          args: 'https://www2.manual.grid.tf -e 404 501 503 504 -w all'
        
  checkwww3:
    name: Check for Broken Links on www3
    runs-on: ubuntu-latest
    steps:
      - name: Check for Broken Links
        id: link-report www3
        uses: docker://ghcr.io/threefoldfoundation/website-link-checker:latest
        with:
          args: 'https://www3.manual.grid.tf -e 404 501 503 504 -w all'